# Netlify Configuration File
# This file configures your Netlify deployment settings

[build]
  # Build command (leave empty for static sites)
  command = ""

  # Directory to publish (root directory for static site)
  publish = "."

# Environment variables (set these in Netlify dashboard)
# API_URL = "https://your-backend-service.com"
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_ANON_KEY = "your-supabase-anon-key"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-service.com/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[build.environment]
  NODE_VERSION = "18"
